# version 屬性已過時，已被移除

services:
  web:
    container_name: meow-circle-web
    image: partnerai/meow-circle:1.0.1
    restart: unless-stopped
    ports:
      - "3000:3000"
    environment:
      # PostgreSQL Database - 在容器中使用服務名稱代替 localhost
      DATABASE_URL: postgresql://postgres:BkgP8eYx4fLz2n7D9vTs5uQmRcK3aHwJ@db:5432/postgres?schema=public
      # Supabase Configuration - 基礎環境變數，用於 entrypoint.sh
      SUPABASE_URL: http://kong:8000
      SUPABASE_ANON_KEY: "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJyb2xlIjoiYW5vbiIsImlzcyI6InN1cGFiYXNlIiwiaWF0IjoxNzQ2NzIwMDAwLCJleHAiOjE5MDQ0ODY0MDB9.y-EksR5ovQHe-DbciTu5vsdCsVqFyyPttJuBwqnBalo"
      SUPABASE_SERVICE_ROLE_KEY: "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJyb2xlIjoic2VydmljZV9yb2xlIiwiaXNzIjoic3VwYWJhc2UiLCJpYXQiOjE3NDY3MjAwMDAsImV4cCI6MTkwNDQ4NjQwMH0.ItPfWnEYsEiL63_G5DEOzusYEBPVp5VX59dgAHhnoIY"
    depends_on:
      - db
      - kong
    networks:
      - supabase_network

# Use the same network as Supabase
networks:
  supabase_network:
    external: true
    name: supabase_default
